name: ProtoType - Deploy to AWS EC2

on:
  push:
    branches:
      - dev

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: MySQL 
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306
        container port: 3306
        mysql database: 'portfolio_test'
        mysql root password: 1234
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: '4.4'

    - name: Setup .env file
      run: |
        echo "TAG_VERSION=${{ secrets.TAG_VERSION }}" >> .env
        echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env
        
        echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
        echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
        echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
        echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env

        echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> .env
        echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> .env
        echo "MONGO_INITDB_DATABASE=${{ secrets.MONGO_INITDB_DATABASE }}" >> .env
        echo "MONGO_INITDB_USERNAME=${{ secrets.MONGO_INITDB_USERNAME }}" >> .env
        echo "MONGO_INITDB_USER_PASSWORD=${{ secrets.MONGO_INITDB_USER_PASSWORD }}" >> .env

        echo "STATIC=${{ secrets.STATIC }}" >> .env
        echo "BUCKET=${{ secrets.BUCKET }}" >> .env
        echo "S3_AWS_ACCESS_KEY=${{ secrets.S3_AWS_ACCESS_KEY }}" >> .env
        echo "S3_AWS_SECRET_KEY=${{ secrets.S3_AWS_SECRET_KEY }}" >> .env
        echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env
        echo "MY_JWT=${{ secrets.MY_JWT }}" >> .env

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker-compose build > build.log 2>&1 || exit 1
        docker-compose push

    - name: Upload Test Reports and Build Logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports-and-logs
        path: |
          app/build/reports/tests/test/
          build.log

  Deploy-DB:
    runs-on: ubuntu-latest
    needs: Build-and-Push
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Copy docker-compose.yml to EC2
      uses: appleboy/scp-action@master
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        host: ${{ secrets.EC2_HOST }} 
        username: ubuntu
        source: "./docker-compose.yml"
        target: "/myconfig/compose/"

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        script: |       
          cd /myconfig/compose

          echo "TAG_VERSION=${{ secrets.TAG_VERSION }}" >> .env
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env

          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env

          echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> .env
          echo "MONGO_INITDB_DATABASE=${{ secrets.MONGO_INITDB_DATABASE }}" >> .env
          echo "MONGO_INITDB_USERNAME=${{ secrets.MONGO_INITDB_USERNAME }}" >> .env
          echo "MONGO_INITDB_USER_PASSWORD=${{ secrets.MONGO_INITDB_USER_PASSWORD }}" >> .env

          echo "STATIC=${{ secrets.STATIC }}" >> .env
          echo "BUCKET=${{ secrets.BUCKET }}" >> .env
          echo "S3_AWS_ACCESS_KEY=${{ secrets.S3_AWS_ACCESS_KEY }}" >> .env
          echo "S3_AWS_SECRET_KEY=${{ secrets.S3_AWS_SECRET_KEY }}" >> .env
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env
          echo "MY_JWT=${{ secrets.MY_JWT }}" >> .env

          sudo docker-compose pull && sudo docker-compose up -d

